# The name of the workflow that will appear in GitHub Actions
name: Build and Push Docker Image
# When to run the workflow
on:
  push:
    branches:
      - main

# Defining the work that needs to be done
jobs:
  build:
    runs-on: ubuntu-latest 
    # Steps to execute in the job
    steps:
        # Step 1: Download the code from the repository
        - name: Checkout code
          uses: actions/checkout@v2
        # Step 2: Preparing Docker Buildx
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        # Step 3: Connecting to DockerHub
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        # Step 4: Building and pushing the Docker image to DockerHub
        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/final-python:latest